SitioWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from aplicaciones.homepage.views import IndexView
from aplicaciones.login.views import LoginFormView, LoginFormView2

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", IndexView.as_view()),
    path("login/", include('aplicaciones.login.urls')),
    path('admin/', admin.site.urls),
    path("erp/", include('aplicaciones.erp.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplicaciones/erp/urls.py
from django.contrib import admin
from django.urls import path, include
from aplicaciones.erp import views
from aplicaciones.erp.views.categoria.views import *
from aplicaciones.erp.views.dashboard.views import *
from aplicaciones.erp.views.cliente.views import *
from aplicaciones.erp.views.producto.views import ProductListView,ProductCreateView, ProductUpdateView, ProductDeleteView

app_name = 'erp'

urlpatterns = [
    path('categoria/list/', CategoryListView.as_view(), name='listarCategoria'),
    path('categoria/add/', CategoryCreateView.as_view(), name='crearCategoria'),
    path('categoria/edit/<int:pk>/', CategoyUpdateView.as_view(), name='editarCategoria'),
    path('categoria/delete/<int:pk>/', CategoyDeleteView.as_view(), name='eliminarCategoria'),
    #Producto
    path('product/list/', ProductListView.as_view(), name='product_list'),
    path('product/add/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    #Cliente
    path('client/list/', ClientListView.as_view(), name='client_list'),
    path('client/add/', ClientCreateView.as_view(), name='client_create'),
    path('client/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    #Dashboard
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    # path('producto/', views.Productos, name='products'),
]

aplicaciones/erp/views/dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator

class DashboardView(TemplateView):
    template_name = 'dashboard.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['panel'] = 'Panel de administrador'
        return context

templates/dashboard.html
{% extends 'layout.html' %}
{% load static %}
{% block head %}
    <script src="{% static 'lib/highcharts-8.1.2/highcharts.js' %}"></script>
    <script src="{% static 'lib/highcharts-8.1.2/modules/exporting.js' %}"></script>
    <script src="{% static 'lib/highcharts-8.1.2/modules/export-data.js' %}"></script>
    <script src="{% static 'lib/highcharts-8.1.2/modules/accessibility.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div id="container"></div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-lg-12">
                <div id="container-pie"></div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-lg-12">
                <div id="container-online"></div>
            </div>
        </div>
        <br>
    </div>
    <script type="application/javascript">
        var graphcolumn = Highcharts.chart('container', {
            chart: {
                type: 'column'
            },
            title: {
                text: 'Reporte de ventas del año 2020'
            },
            subtitle: {
                text: 'Reporte de columnas'
            },
            xAxis: {
                categories: [
                    'Enero',
                    'Febrero',
                    'Marzo',
                    'Abril',
                    'Mayo',
                    'Junio',
                    'Julio',
                    'Agosto',
                    'Septiembre',
                    'Octubre',
                    'Noviembre',
                    'Diciembre'
                ],
                crosshair: true
            },
            yAxis: {
                min: 0,
                title: {
                    text: 'Valores $'
                }
            },
            tooltip: {
                headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                    '<td style="padding:0"><b>{point.y:.1f} $</b></td></tr>',
                footerFormat: '</table>',
                shared: true,
                useHTML: true
            },
            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                }
            },
        });

        var graphpie = Highcharts.chart('container-pie', {
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false,
                type: 'pie'
            },
            title: {
                text: 'Porcentaje de venta de productos por el mes de Junio del año 2020'
            },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            accessibility: {
                point: {
                    valueSuffix: '%'
                }
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: true,
                        format: '<b>{point.name}</b>: {point.percentage:.1f} %'
                    }
                }
            },
        });

        /*Highcharts.chart('container-online', {
            chart: {
                type: 'spline',
                animation: Highcharts.svg, // don't animate in old IE
                marginRight: 10,
                events: {
                    load: function () {
                        var series = this.series[0];
                        setInterval(function () {
                            $.ajax({
                                url: window.location.pathname, //window.location.pathname
                                type: 'POST',
                                data: {
                                    'action': 'get_graph_online'
                                },
                                dataType: 'json',
                            }).done(function (data) {
                                if (!data.hasOwnProperty('error')) {
                                    var x = (new Date()).getTime();
                                    series.addPoint([x, data.y], true, true);
                                    return false;
                                }
                                message_error(data.error);
                            }).fail(function (jqXHR, textStatus, errorThrown) {
                                alert(textStatus + ': ' + errorThrown);
                            }).always(function (data) {

                            });
                        }, 1000);
                    }
                }
            },

            time: {
                useUTC: false
            },

            title: {
                text: 'Live random data'
            },

            accessibility: {
                announceNewData: {
                    enabled: true,
                    minAnnounceInterval: 15000,
                    announcementFormatter: function (allSeries, newSeries, newPoint) {
                        if (newPoint) {
                            return 'New point added. Value: ' + newPoint.y;
                        }
                        return false;
                    }
                }
            },

            xAxis: {
                type: 'datetime',
                tickPixelInterval: 150
            },

            yAxis: {
                title: {
                    text: 'Value'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },

            tooltip: {
                headerFormat: '<b>{series.name}</b><br/>',
                pointFormat: '{point.x:%Y-%m-%d %H:%M:%S}<br/>{point.y:.2f}'
            },

            legend: {
                enabled: false
            },

            exporting: {
                enabled: false
            },

            series: [{
                name: 'Random data',
                data: (function () {
                    // generate an array of random data
                    var data = [],
                        time = (new Date()).getTime(),
                        i;

                    for (i = -19; i <= 0; i += 1) {
                        data.push({
                            x: time + i * 1000,
                            y: Math.random()
                        });
                    }
                    return data;
                }())
            }]
        });*/

        function get_graph_sales_year_month() {
            $.ajax({
                url: window.location.pathname, //window.location.pathname
                type: 'POST',
                data: {
                    'action': 'get_graph_sales_year_month'
                },
                dataType: 'json',
            }).done(function (data) {
                if (!data.hasOwnProperty('error')) {
                    graphcolumn.addSeries(data);
                    return false;
                }
                message_error(data.error);
            }).fail(function (jqXHR, textStatus, errorThrown) {
                alert(textStatus + ': ' + errorThrown);
            }).always(function (data) {

            });
        }

        function get_graph_sales_products_year_month() {
            $.ajax({
                url: window.location.pathname, //window.location.pathname
                type: 'POST',
                data: {
                    'action': 'get_graph_sales_products_year_month'
                },
                dataType: 'json',
            }).done(function (data) {
                if (!data.hasOwnProperty('error')) {
                    graphpie.addSeries(data);
                    return false;
                }
                message_error(data.error);
            }).fail(function (jqXHR, textStatus, errorThrown) {
                alert(textStatus + ': ' + errorThrown);
            }).always(function (data) {

            });
        }

        $(function () {

            get_graph_sales_year_month();

            get_graph_sales_products_year_month();

        });
    </script>
{% endblock %}

templates/delete.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% block content %}
    <form method="post" action=".">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">
                    {% if action == 'add' %}
                        <i class="fas fa-plus"></i>
                    {% else %}
                        <i class="fas fa-trash"></i>
                    {% endif %}
                    {{ title }}
                </h3>
            </div>

            <div class="card-body">
                {% csrf_token %}

                <input type="hidden" name="action" value="{{ action }}">
                {% if action %}

                {% endif %}

                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>

                                {% endfor %}
                            {% endfor %}

                        </ul>


                    </div>
                {% endif %}
            </div>

            <div class="alert alert-danger  alert-dismissible">
                <h5><i class="icon fas fa-ban"></i> Notificación!</h5>
                ¿Estas seguro de eliminar el registro {{ object.name }}?
            </div>

            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-flat">
                    <i class="fas fa-save"></i> Aceptar
                </button>
                <a href="{{ list_url }}" type="submit" class="btn btn-info btn-flat">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>


        </div>
    </form>


{% endblock %}

templates/footer.html
<!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; <span id="currentYear"></span> </strong> All rights reserved.
</footer>


 <script>
        // Obtener el elemento span con el ID 'currentYear'
        var currentYearElement = document.getElementById('currentYear');

        // Obtener el año actual
        var currentYear = new Date().getFullYear();

        // Asignar el año actual al elemento span
        currentYearElement.textContent = currentYear;
    </script>

templates/form.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% block content %}
    <form method="post" action="." enctype="multipart/form-data">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">
                    {% if action == 'add' %}
                        <i class="fas fa-plus"></i>
                    {% else %}
                        <i class="fas fa-edit"></i>
                    {% endif %}
                    {{ title }}
                </h3>
            </div>

            <div class="card-body">
                {% csrf_token %}

                <input type="hidden" name="action" value="{{ action }}">
                {% if action %}

                {% endif %}

                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>

                                {% endfor %}
                            {% endfor %}

                        </ul>


                    </div>
                {% endif %}

                {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label for="email">{{ field.label }}:</label>
                        {{ field|add_class:'form-control'|attr:'autocomplete:off' }}
                    </div>
                {% endfor %}


            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-flat">
                    <i class="fas fa-save"></i> Guardar Registro
                </button>
            </div>

        </div>
    </form>
    <script>

        {% if form.errors %}
            var errors = '';
            {% for field in form %}
                {% for error in field.errors %}
                    errors += '{{ error }}\n';

                {% endfor %}

            {% endfor %}
            Swal.fire({
                title: 'Error!',
                text: errors,
                icon: 'error',
            })
        {% endif %}

        {##}
        {#        PARTE DE CODIGO PARA TRABAJAR CON AJAX#}
        {#        $('form').on('submit', function (e) {#}
        {#            e.preventDefault();#}
        {#           // obtener a manera de diccionario todos los datos del diccionario#}
        {#            var parameters = $(this).serializeArray();#}
        {##}
        {#            $.ajax({#}
        {#                url: '{% url 'erp:crearCategoria' %}',#}
        {#                type: 'POST',#}
        {#                data: parameters,#}
        {#                dataType: 'json'#}
        {##}
        {#            }).done(function (data) {#}
        {#                if (!data.hasOwnProperty('error')){#}
        {#                    Location.href = '{{ list_url }}'#}
        {#                    return false;#}
        {#                }#}
        {#                message_error(data.error);#}
        {#            }).fail(function (data) {#}
        {##}
        {#            }).always(function (data) {#}
        {##}
        {#            })#}
        {#        });#}


    </script>


{% endblock %}

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{{ title }}</title>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- jQuery -->
    <script src="{% static 'lib/adminlte-3.2.0/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/adminlte-3.2.0/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/adminlte-3.2.0/js/adminlte.min.js' %}"></script>
    <!-- Sweetalert2 -->
    <script src="{% static 'lib/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>
    <!-- funciones -->
    <script src="{% static 'js/functions.js' %}"></script>

    <!-- Cloque head -->
    {% block head %}


    {% endblock %}

</head>

{% block body %}

{% endblock %}


</html>

templates/layout.html
{% extends 'vtc/body.html' %}

templates/list.html
{% extends 'layout.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet"
          href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}"/>
    <script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>
{% endblock %}


{% block content %}
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">
                <i class="fas fa-search"></i>
                {{ title }}
            </h3>
        </div>

        <div class="card-body">
            <table class="table" id="data">
                <thead>
                {% block columns %}

                {% endblock %}

                </thead>
                <tbody>
                {% block rows %}

                {% endblock %}

                </tbody>
            </table>
        </div>
        <div class="card-footer">
            <a href="{{ create_url }}" class="btn btn-primary btn-flat btnTest">
                <i class="fas fa-plus"></i> Nuevo registro
            </a>
        </div>

    </div>


{% endblock %}



{% block javascript %}
    <script type="application/javascript">
        $(function () {
            $('#data').DataTable({
                responsive: true, //Autoajusta el contenido de la tabla responsive
                autoWidth: false //Respeta el ancho que se le de a cada columna
            });

            $('.btnTest').on('click', function () {
                $.ajax({
                    url: '{% url 'erp:listarCategoria' %}',
                    type: 'POST',
                    data: {id: 1},
                    dataType: 'json'

                }).done(function (data) {
                    console.log(data);
                }).fail(function (data) {

                }).always(function (data) {

                })
            });

        })

    </script>
{% endblock %}

templates/tests.html
{% extends 'layout.html' %}
{% load widget_tweaks %}
{% load static %}
{% block head %}
    <link href="{% static 'lib/jquery-ui-1.12.1/jquery-ui.min.css' %}" rel="stylesheet"/>
    <script src="{% static 'lib/jquery-ui-1.12.1/jquery-ui.min.js' %}"></script>

    <link href="{% static 'lib/select2-4.0.13/css/select2.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'lib/select2-4.0.13/css/select2-bootstrap4.min.css' %}" rel="stylesheet"/>
    <script src="{% static 'lib/select2-4.0.13/js/select2.min.js' %}"></script>
    <script src="{% static 'lib/select2-4.0.13/js/i18n/es.js' %}"></script>
{% endblock %}
{% block content %}
    <form method="post" action="." enctype="multipart/form-data">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-plus"></i>
                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label>Categorias:</label>
                    {{ form.categories }}
                </div>
                <div class="form-group">
                    <label>Productos:</label>
                    {{ form.products }}
                </div>
                <div class="form-group">
                    <label>Buscador:</label>
                    {{ form.search }}
                </div>
            </div>
        </div>
    </form>
    <script>
        var select_products = $('select[name="products"]');
        $(function () {

            $('.select2').select2({
                theme: "bootstrap4",
                language: 'es'
            });

            $('select[name="categories"]').on('change', function () {
                var id = $(this).val();
                var options = '<option value="">--------------------</option>';
                if (id === '') {
                    select_products.html(options);
                    return false;
                }
                $.ajax({
                    url: window.location.pathname,
                    type: 'POST',
                    data: {
                        'action': 'search_product_id',
                        'id': id
                    },
                    dataType: 'json',
                }).done(function (data) {
                    if (!data.hasOwnProperty('error')) {
                        select_products.html('').select2({
                            theme: "bootstrap4",
                            language: 'es',
                            data: data
                        });
                        /*$.each(data, function (key, value) {
                            options += '<option value="' + value.id + '">' + value.name + '</option>';
                        });*/
                        return false;
                    }
                    message_error(data.error);
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert(textStatus + ': ' + errorThrown);
                }).always(function (data) {
                    //select_products.html(options);
                });
            });

            select_products.on('change', function () {
                var value = select_products.select2('data')[0];
                console.log(value);
            });

            var availableTags = [
                "ActionScript",
                "AppleScript",
                "Asp",
                "BASIC",
                "C",
                "C++",
                "Clojure",
                "COBOL",
                "ColdFusion",
                "Erlang",
                "Fortran",
                "Groovy",
                "Haskell",
                "Java",
                "JavaScript",
                "Lisp",
                "Perl",
                "PHP",
                "Python",
                "Ruby",
                "Scala",
                "Scheme"
            ];

            $('input[name="search"]').autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: window.location.pathname,
                        type: 'POST',
                        data: {
                            'action': 'autocomplete',
                            'term': request.term
                        },
                        dataType: 'json',
                    }).done(function (data) {
                        response(data);
                    }).fail(function (jqXHR, textStatus, errorThrown) {
                        //alert(textStatus + ': ' + errorThrown);
                    }).always(function (data) {

                    });
                },
                delay: 500,
                minLength: 1,
                select: function (event, ui) {
                    console.log(ui.item);
                }
            });

            $('select[name="search"]').select2({
                theme: "bootstrap4",
                language: 'es',
                allowClear: true,
                ajax: {
                    delay: 250,
                    type: 'POST',
                    url: window.location.pathname,
                    data: function (params) {
                        var queryParameters = {
                            term: params.term,
                            action: 'autocomplete'
                        }
                        return queryParameters;
                    },
                    processResults: function (data) {
                        return {
                            results: data
                        };
                    },
                },
                placeholder: 'Ingrese una descripción',
                minimumInputLength: 1,
            });
        });
    </script>
{% endblock %}

templates/ticket.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<div class="container">
  <h2 class="text-uppercase">{{ name }}</h2>
  <p>The .table class adds basic styling (light padding and horizontal dividers) to a table:</p>
  <table class="table">
    <thead>
      <tr>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>John</td>
        <td>Doe</td>
        <td>john@example.com</td>
      </tr>
      <tr>
        <td>Mary</td>
        <td>Moe</td>
        <td>mary@example.com</td>
      </tr>
      <tr>
        <td>July</td>
        <td>Dooley</td>
        <td>july@example.com</td>
      </tr>
    </tbody>
  </table>
</div>

</body>
</html>